baseURL = "https://lightbi-hugo-theme.netlify.app/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Lightbi"
theme = "lightbi"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
Paginate = 6

[Params] 
mainSections = ["post"]
dateFormat = "January 2, 2020"
favicon = "img/favicon.ico"
comments = false
readingTime = false
wordCount = false
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "9"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Bino Kochumol Varghese"
  website = "https://www.binovarghese.com"
  email = "sample@gmail.com"
  facebook = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  twitter = "username"
  linkedin = "username"
  github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Haiku"
    url = "/haiku/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3



