name = "LightBi"
license = "MIT"
licenselink = "https://github.com/binokochumolvarghese/lightbi-hugo/blob/master/LICENSE"
description = "Minimal personal website and blog theme Hugo. Forked from Beautiful Hugo."
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "mobile", "technical"]
min_version = 0.02

[author]
    name = "Bino Kochumol Varghese"
    homepage = "http://binovarghese.com"

