name = "LightBi Hugo"
license = "MIT"
licenselink = "https://github.com/halogenica/Hugo-BeautifulHugo/blob/master/LICENSE"
description = "An adaptation of the Beautiful Jekyll theme"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "mobile", "technical"]
min_version = 0.01

[author]
    name = "Bino Kochumol Varghese"
    homepage = "http://binovarghese.com"

# If Porting existing theme
[original]
    name = "halogenica"
    homepage = "http://halogenica.net"
